spring:
  application:
    name: w-login
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tiger

server:
  port: 9001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      login: INFO
    root: WARN
    org:
      springframework: WARN
