spring:
  application:
    name: w-teacher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tiger
  jpa:
    hibernate:
     ddlAuto: update

server:
  port: 9003

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      teacher: INFO
    root: WARN
    org:
      springframework: WARN

kafka:
  topic:
    student: W_STUDENT
    feedback: W_FEEDBACK
  producer:
    url: http://kafka-producer/producer/send/

