spring:
  application:
    name: w-login-listener
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tiger
  jpa:
    hibernate:
     ddlAuto: update

kafka:
  bootstrap-servers: localhost:9092
  enable-auto-commit: false
  auto-commit-interval-ms: 100
  session-timeout-ms: 15000
  group-id: springboot-workshop
  auto-offset-reset: earliest
  topic:
    logintopic: W_LOGIN

server:
  port: 8001

logging:
  level:
    com:
      login:
        listener: INFO
    root: WARN
    org:
      springframework: WARN
